### PR TITLE
Add favicon & brand logo

### PR DESCRIPTION
**Pull request by mm-vasyl**
Simply adds a favicon and `.monks` × custom client logo

To add a logo, update `settings` with:
```
"client": "./img/bmw.svg",
```

Works only with local images*

You can see the result here: [https://richmedia-previews-s3bucket-tu6a9uv81tss.s3.amazonaws.com/test-bmw-template/index.html](https://richmedia-previews-s3bucket-tu6a9uv81tss.s3.amazonaws.com/test-bmw-template/index.html)

### CODE REVIEW

**Comment by mm-paulie** [comment]
https://github.com/user-attachments/assets/17a6413f-1171-4ff3-8435-9d318190096e
Wow this sooo awesome!  I just noticed though that local images don't seem to work?

**Comment by PabloCarreira** [comment]
Same issue here. I couldn't make it work with a local svg image from the img folder on Shared.
I think this is a Must since targeting a logo from client web products wont be as easy. Also gives more customization to apply an svg local from the project.

Thanks for the quick update Vasyl!

**Comment by mm-vasyl** [comment]
Local logos support added, http removed for simplicity.

**Review by PabloCarreira — APPROVED** [review]
Beautiful!
Thanks Vasyl

**Review by xaviergdiez84 — APPROVED** [review]
Approved!!

**Pull request merged**
