### PR TITLE
Adds page and perpage url params for init pagination

### LINKED ISSUE #87: Option to go to a certain page via the url vars
issue_pages
Would be great to have this feature in the url of your page, something like
page=1

### PR DESCRIPTION
**Pull request by mm-vasyl**
resolves #87

### CODE REVIEW

**Comment by mm-vasyl** [comment]
`+var` == Number(var)

just fyi

image

**Review by mm-paulie — APPROVED** [review]

**Review by xaviergdiez84 — APPROVED** [review]
:)

**Comment by mm-paulie** [comment]
@mm-vasyl would love to merge this request but we must resolve the index_bundle.js, can you do that on your branch by re-building and pushing it?

**Comment by mm-vasyl** [comment]
hey @mm-paulie we're all set!

**Pull request merged**
