### PR TITLE
Check extension

### PR DESCRIPTION
**Pull request by luckyone29**
Add new helper))

### CODE REVIEW

**Comment by luckyone29** [comment]
{{#checkExtension this.subTitle '.png|.jpg|.jpeg'}}
  
{{else}}
  <div class="subTitle--{{@index}} subTitle">{{{this.title}}}</div>
{{/checkExtension}}

**Comment by xaviergdiez84** [comment]
Looks good!

**Review by xaviergdiez84 — APPROVED** [review]

**Comment by mm-paulie** [comment]
I just checked the display-dev-server. And it seems that, before Serhiy, Mirko worked on the master, he changed quite  a lot, but never made a new version out of this. But of course Serhiy worked on top of this, and that part seems to be breaking up the display-dev-server now. I will try and fix it.

**Review by mm-paulie — CHANGES_REQUESTED** [review]
Can you update the pull request? With the latest amends from the master? The master had issues and these were also into your branch, if you update your branch and update your pull request we can officially approve it 
You can probably do something in your branch, on github.com, like "sync fork" @luckyone29

**Pull request merged**
